import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";

import { cn } from "@/src/lib/utils";

import { Providers } from "@/src/providers";
import { Header } from "@/src/components/Header";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Warp Assessment - FE",
  description: "Generated by create next app",
  // icons: { icon: Logo },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          roboto.variable,
          "flex min-h-screen flex-col pb-6 font-medium antialiased",
        )}
      >
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
